In [12]:
from tensorflow.python.keras import layers
from tensorflow.python.keras import backend
import tensorflow as tf
import numpy as np

a = np.zeros((2, 2, 3))
b = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
print(backend.expand_dims(b, axis=-2))
c = backend.tile(backend.expand_dims(b, axis=-2), (1, 80, 1))

tf.Tensor(
[[[1 2 3]]

 [[4 5 6]]], shape=(2, 1, 3), dtype=int32)


In [2]:
import tensorflow as tf
import numpy as np

a = tf.constant([[[1, 1],
                  [2, 1]],
                 [[3,2],
                 [5, 3]]])
print(a.shape)
a = np.array(a)
print(a.reshape((a.shape[0] * 2, a.shape[-1])))
b = np.arange(1, a.shape[0] + 1)
a = np.vstack([b, a])
a = np.transpose(a, axes=(1, 0))
import pandas
a = pandas.DataFrame(a, columns=['id', 'pressure'])
a.to_csv('./test_sub.csv')

(2, 2, 2)
[[1 1]
 [2 1]
 [3 2]
 [5 3]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)

In [ ]:
class ExpandLayer(layers.Layer):
    def __init__(self):
        super(ExpandLayer, self).__init__()
    def call(self, inputs, *args, **kwargs):
        return backend.expand_dims(inputs, axis=-1)
c = layers.Concatenate(axis=-1)([a, b])
print(c)